AUG_TEST: simple_augment_test
AUG_TEST_PARAMS: null
AUG_TRAIN: randaugment_train
AUG_TRAIN_PARAMS:
  n_select: 0
BATCH_SIZE: 32
DATASET: TACO
DATA_PATH: ../data
EPOCHS: 100
IMG_SIZE: 32
INIT_LR: 0.0001
VAL_RATIO: 0.8
